# Generated by Django 6.0.5 on 2026-06-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('TEACHING', 'Teaching'), ('SUPPORT', 'Support')], default='', max_length=20),
        ),
    ]
