# Generated by Django 6.0.5 on 2026-07-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_staffmember_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('TEACHING', 'Teaching'), ('SUPPORT', 'Support'), ('LEADER', 'Senior leader')], default='', max_length=20),
        ),
    ]
