# Generated by Django 6.0.5 on 2026-06-29 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_staffmember_staff_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('meeting_date', models.DateField()),
                ('actions_from_last_meeting', models.TextField(blank=True, default='')),
                ('upcoming', models.TextField(blank=True, default='')),
                ('rotation_update', models.TextField(blank=True, default='')),
                ('main_matters', models.TextField(blank=True, default='')),
                ('actions_from_meeting', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_meetings', to='core.staffmember')),
            ],
            options={
                'ordering': ['-meeting_date', '-created_at'],
                'indexes': [models.Index(fields=['staff', '-meeting_date'], name='line_manage_staff_i_ba44bc_idx')],
            },
        ),
    ]
