# Generated by Django 6.0.5 on 2026-09-30 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rag', models.CharField(blank=True, choices=[('RED', 'Red'), ('AMBER', 'Amber'), ('GREEN', 'Green')], default='', max_length=5)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreed_at', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreed_actions', to='line_management.linemeeting')),
                ('reviewed_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_actions', to='line_management.linemeeting')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('reviewed_in', models.F('agreed_at')), _negated=True), name='meetingaction_not_reviewed_where_agreed'), models.CheckConstraint(condition=models.Q(('rag__in', ['', 'RED', 'AMBER', 'GREEN'])), name='meetingaction_rag_valid'), models.CheckConstraint(condition=models.Q(('reviewed_in__isnull', False), models.Q(('rag', ''), ('review_comment', '')), _connector='OR'), name='meetingaction_rating_needs_review_meeting')],
            },
        ),
    ]
