# Generated by Django 6.0.5 on 2026-10-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_normalise_emails'),
        ('line_management', '0002_meetingaction'),
    ]

    operations = [
        # HAND-CHECKED (leg 3 of docs/chart/line-meeting-preparation.md). Every
        # meeting that exists before this migration was held, so the column's
        # *database* default is HELD: Postgres fills existing rows with it, and
        # it stays in place for the previous release, which keeps serving while
        # a deploy migrates and inserts without this column. The Python default
        # (PREPARING) is what the app writes. A plain default='PREPARING' — what
        # makemigrations first generated — would have put every existing meeting
        # into "Being prepared", and the one-preparing-per-staff constraint below
        # would then fail for anyone with two meetings, aborting the deploy.
        migrations.AddField(
            model_name='linemeeting',
            name='state',
            field=models.CharField(choices=[('PREPARING', 'Being prepared'), ('HELD', 'Held')], db_default='HELD', default='PREPARING', max_length=9),
        ),
        migrations.AddConstraint(
            model_name='linemeeting',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'PREPARING')), fields=('staff',), name='linemeeting_one_preparing_per_staff', violation_error_message='This person already has a meeting being prepared.'),
        ),
        migrations.AddConstraint(
            model_name='linemeeting',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['PREPARING', 'HELD'])), name='linemeeting_state_valid'),
        ),
    ]
