# Generated by Django 6.0.5 on 2026-06-24 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_staffmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SHARED', 'Shared'), ('SIGNED_OFF', 'Signed off')], default='DRAFT', max_length=20)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('cpd_requirements', models.TextField(blank=True, default='')),
                ('summary_teacher_comment', models.TextField(blank=True, default='')),
                ('summary_coach_comment', models.TextField(blank=True, default='')),
                ('job_description_review_needed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='appraisals.academicyear')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='core.staffmember')),
            ],
            options={
                'ordering': ['-academic_year__start_year'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('STANDARDS', 'Standards & policies'), ('PERSONAL', 'Personal goal'), ('LEADERSHIP', 'Leadership / UPR')], max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.TextField(blank=True, default='')),
                ('steps_to_success', models.TextField(blank=True, default='')),
                ('success_criteria', models.TextField(blank=True, default='')),
                ('teacher_review_comment', models.TextField(blank=True, default='')),
                ('coach_review_comment', models.TextField(blank=True, default='')),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='appraisals.appraisal')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='appraisal',
            constraint=models.UniqueConstraint(fields=('teacher', 'academic_year'), name='unique_appraisal_per_teacher_year'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(fields=('appraisal', 'order'), name='unique_goal_order_per_appraisal'),
        ),
    ]
