# Generated by Django 6.0.5 on 2026-06-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='coach_supports_pay_award',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NOT_APPLICABLE', 'Not applicable')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='engaged_with_professional_growth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='on_upper_pay_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='self_review_form_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='job_description_review_needed',
            field=models.BooleanField(default=False),
        ),
    ]
