# Generated by Django 6.0.5 on 2026-06-24 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0002_appraisal_coach_supports_pay_award_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TEACHING', 'Teaching'), ('SUPPORT', 'Support')], max_length=20)),
                ('job_summary', models.TextField(blank=True, default='')),
                ('level_description', models.TextField(blank=True, default='')),
                ('upr_declaration_agreed', models.BooleanField(default=False)),
                ('signed_name', models.CharField(blank=True, default='', max_length=200)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_review', to='appraisals.appraisal')),
            ],
        ),
        migrations.CreateModel(
            name='SelfReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('code', models.CharField(max_length=20)),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('descriptor', models.TextField()),
                ('met', models.BooleanField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, default='')),
                ('self_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appraisals.selfreview')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('self_review', 'code'), name='unique_item_code_per_self_review')],
            },
        ),
    ]
