# Generated by Django 6.0.5 on 2026-07-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0006_remove_selfreviewitem_descriptor_and_met'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appraisal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_review', to='appraisals.appraisal')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('goal', models.TextField(blank=True, default='')),
                ('evidence_and_discussion', models.TextField(blank=True, default='')),
                ('achieved', models.BooleanField(blank=True, null=True)),
                ('leader_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='appraisals.leaderreview')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LeaderStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('descriptors', models.TextField(blank=True, default='')),
                ('score', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('not_applicable', models.BooleanField(default=False)),
                ('examples', models.TextField(blank=True, default='')),
                ('leader_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='appraisals.leaderreview')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('leader_review', 'number'), name='unique_standard_number_per_leader_review')],
            },
        ),
    ]
