# Generated by Django 6.0.5 on 2026-07-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0007_leaderreview_leadergoal_leaderstandard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadergoal',
            name='leader_review',
        ),
        migrations.AlterModelOptions(
            name='leaderstandard',
            options={'ordering': ['section', 'order']},
        ),
        migrations.RemoveConstraint(
            model_name='leaderstandard',
            name='unique_standard_number_per_leader_review',
        ),
        migrations.AddField(
            model_name='leaderstandard',
            name='section',
            field=models.CharField(choices=[('ETHICS', 'Ethics and Professional Conduct'), ('STANDARDS', "Headteacher's Standards")], default='STANDARDS', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='leaderstandard',
            constraint=models.UniqueConstraint(fields=('leader_review', 'section', 'number'), name='unique_standard_number_per_leader_review'),
        ),
        migrations.DeleteModel(
            name='LeaderGoal',
        ),
    ]
