# Generated by Django 6.0.5 on 2026-07-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0008_remove_leadergoal_leader_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraisal',
            options={'ordering': ['-academic_year__start_year'], 'verbose_name': 'Goal Setting and Review', 'verbose_name_plural': 'Goal Setting and Reviews'},
        ),
    ]
