# Generated by Django 6.0.5 on 2026-06-30 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('STAFF', 'Staff'), ('APPRAISAL_SUMMARY', 'Appraisal summaries'), ('GOALS', 'Goals'), ('SELF_REVIEW', 'Self-review'), ('LINE_MEETINGS', 'Line meetings')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DISCARDED', 'Discarded')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('create_count', models.PositiveIntegerField(default=0)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('STAFF', 'Staff'), ('APPRAISAL_SUMMARY', 'Appraisal summaries'), ('GOALS', 'Goals'), ('SELF_REVIEW', 'Self-review'), ('LINE_MEETINGS', 'Line meetings')], max_length=30)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_json', models.JSONField()),
                ('outcome', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('SKIP', 'Skip')], max_length=10)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('source_row_hash', models.CharField(max_length=64)),
                ('created_object_model', models.CharField(blank=True, choices=[('StaffMember', 'StaffMember'), ('Appraisal', 'Appraisal'), ('Goal', 'Goal'), ('SelfReviewBullet', 'SelfReviewBullet'), ('LineMeeting', 'LineMeeting')], default='', max_length=30)),
                ('created_object_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='data_import.importbatch')),
            ],
            options={
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['batch', 'row_number'], name='data_import_batch_i_af851f_idx'), models.Index(fields=['import_type', 'source_row_hash'], name='data_import_import__3406bf_idx')],
            },
        ),
    ]
