# Generated by Django 6.0.5 on 2026-09-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='clear_blank_fields',
            field=models.BooleanField(default=False),
        ),
    ]
